language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
notifications:
  email: false

install:
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  code_climate:
      repo_token: b4da0635e6572389e8bbc1e4a67ccd5930f371f221b5d5065efafd6c81f78fa0


